### ISSUE TITLE
Classe "Locacao"- Método: CalcularValorTotal

### ISSUE THREAD

**Issue by Destraiker** [Destraiker/Locadora#34]
calcularValorTotal: calcula o valor total que o cliente deve pagar, incluindo valor
das di´arias, multas e manuten¸c˜oes.

**Comment by OtavioZoka** [comment]
valor das doenças?! KKKKKKKKKKKKKKKKKKKKKKKK

**Comment by Destraiker** [comment]
Doente é vc moleke?
